AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
    
  LambdaToInvokeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdaToInvoke/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        LambdaToInvoke:
          Type: Api 
          Properties:
            Path: /invoke
            Method: get

  InvokerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: invoker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Invoker:
          Type: Api 
          Properties:
            Path: /receive
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  LambdaToInvokeApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invoke/"
  LambdaToInvokeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaToInvokeFunction.Arn
  LambdaToInvokeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaToInvokeFunctionRole.Arn
  InvokerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/receive/"
  InvokerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaToInvokeFunction.Arn
  InvokerunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaToInvokeFunctionRole.Arn
